export { default as SVGCore } from './SVGCore.svg'
export { default as SVGLead } from './SVGLead.svg'
export { default as SVGOrg } from './SVGOrg.svg'
export { default as SVGTm } from './SVGTm.svg'
export { default as SVGGithub } from './SVGGithub.svg'
